//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace matriculacion_proy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_matriculacion_proyEntities2 : DbContext
    {
        public db_matriculacion_proyEntities2()
            : base("name=db_matriculacion_proyEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_agencia> tbl_agencia { get; set; }
        public virtual DbSet<tbl_color> tbl_color { get; set; }
        public virtual DbSet<tbl_marca> tbl_marca { get; set; }
        public virtual DbSet<tbl_matricula> tbl_matricula { get; set; }
        public virtual DbSet<tbl_usuario> tbl_usuario { get; set; }
        public virtual DbSet<tbl_vehiculo> tbl_vehiculo { get; set; }
    }
}
