//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace matriculacion_proy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_vehiculo()
        {
            this.tbl_matricula = new HashSet<tbl_matricula>();
        }
    
        public int idVehiculo { get; set; }
        public string placaVehiculo { get; set; }
        public string motorVehiculo { get; set; }
        public string chasisVehiculo { get; set; }
        public string combustibleVehiculo { get; set; }
        public string anioVehiculo { get; set; }
        public decimal avaluoVehiculo { get; set; }
        public string fotoVehiculo { get; set; }
        public Nullable<int> idMarca { get; set; }
        public Nullable<int> idColor { get; set; }
        public Nullable<int> idUsuario { get; set; }
    
        public virtual tbl_color tbl_color { get; set; }
        public virtual tbl_marca tbl_marca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_matricula> tbl_matricula { get; set; }
        public virtual tbl_usuario tbl_usuario { get; set; }
    }
}
